context.properties = {
    # Force a stable default clock rate
    default.clock.rate          = 48000
    default.clock.allowed-rates = [ 48000 ]
    
    # Adjust quantum (buffer) sizes to prevent underruns
    default.clock.quantum       = 1024
    default.clock.min-quantum   = 1024
    default.clock.max-quantum   = 1024
}

context.properties.rules = [
    {
        matches = [ { cpu.vm.type = "none" } ]
        actions = {
            update-props = {
                mem.warn-mlock = false
            }
        }
    }
]

node.properties = {
    clock.power-of-two-quantum = false
}
